#!/usr/bin/env bash
set -e

if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

cd /etc/nixos

nixos-rebuild switch --flake .
echo "Created new generation"

nix-collect-garbage --delete-old
echo "Garbage collection completed"

nixos-rebuild switch --flake .
echo "Finished updating NixOS configuration"