#!/usr/bin/env bash
set -e

if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

nixos-rebuild switch --flake github:AlexWright1324/nixos-configuration#Alex-PC-NixOS --no-write-lock-file