#!/usr/bin/env bash
set -e

if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

cd /etc/nixos

git fetch origin
git checkout main
git reset --hard origin/main
git clean -f -d

nix flake update
nixos-rebuild switch --flake .#Alex-PC-NixOS
