name: Update flake inputs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1' # Mondays at 04:00 UTC

permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write

concurrency:
  group: flake-update
  cancel-in-progress: false

jobs:
  flake-update:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      NIXPKGS_ALLOW_UNFREE: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Install Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update Nix flake inputs"
          pr-labels: |
            dependencies
            automated
          nix-options: "--access-tokens github.com=${{ secrets.GH_TOKEN_FOR_UPDATES }}"
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
